dist: xenial
os: linux
language: python
python:
  - '3.8'
branches:
  only:
  - master
  - develop
install:
  - pip install awscli
  - pip install aws-sam-cli
  - pip install -r pps/core-layer/requirements.txt
  - pip install -r pps/core-layer/requirements.txt --target ./pps/core-layer/python
  - pip install pytest
  - cd web && npm install && npm run build
  - cd ..
script:
  - pytest .
  - sam validate
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
    - AWS_DEFAULT_REGION=us-west-2