AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pps-api

  Personal Progression System for the Guides and Scouts movement.

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        WEB_APP_DOMAIN: !GetAtt CloudfrontDistribution.DomainName
        WEB_APP_BUCKET: !Ref S3BucketWebApp
        GALLERY_BUCKET: !Ref S3BucketGallery
        COGNITO_CLIENT_ID: !Ref UsersClient
        USER_POOL_ID: !Ref UsersPool

Resources:
  PPSAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: PPSAPI
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: UsersAuthorizer
        Authorizers:
          UsersAuthorizer:
            UserPoolArn: !GetAtt UsersPool.Arn
      Models:
        ScouterSignUp:
          type: object
          required:
            - email
            - password
            - name
            - family_name
          properties:
            email:
              type: string
            password:
              type: string
            name:
              type: string
            middle_name:
              type: string
            family_name:
              type: string
        BeneficiarySignUp:
          type: object
          required:
            - email
            - password
            - name
            - family_name
            - birthdate
            - gender
          properties:
            email:
              type: string
            password:
              type: string
            name:
              type: string
            middle_name:
              type: string
            family_name:
              type: string
            birth_date:
              type: string
            unit:
              type: string
        Code:
          type: object
          required:
            - code
          properties:
            code:
              type: string
        Login:
          type: object
          required:
            - email
            - password
          properties:
            email:
              type: string
            password:
              type: string
        RefreshToken:
          type: object
          required:
            - token
          properties:
            token:
              type: string
        NewGroup:
          type: object
          required:
            - name
          properties:
            name:
              type: string
        StartObjective:
          type: object
          required:
            - stage
            - tasks
            - objective
          properties:
            stage:
              type: string
            tasks:
              type: list
            objective:
              type: object
              properties:
                area:
                  type: string
                line:
                  type: integer
  PPSAPIValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      Name: PPSAPIValidator
      RestApiId: !Ref PPSAPI
      ValidateRequestBody: true
      ValidateRequestParameters: false
  # Core Layer
  PPSCore:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: PPSCore
      Description: Core of the Personal Progression System
      CompatibleRuntimes:
        - python3.8
      ContentUri: pps/core-layer/
  # Cognito
  UsersPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: Users
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Required: true
        - Name: middle_name
          AttributeDataType: String
          Required: false
        - Name: family_name
          AttributeDataType: String
          Required: true
        - Name: gender
          AttributeDataType: String
          Required: false
        - Name: birthdate
          AttributeDataType: String
          Required: false
        - Name: nickname
          AttributeDataType: String
          Required: false
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
  UsersClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: UsersClient
      UserPoolId: !Ref UsersPool
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      WriteAttributes:
        - name
        - middle_name
        - family_name
        - gender
        - birthdate
        - nickname
  UsersScoutersGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Scouters
      Description: Scouters group
      UserPoolId: !Ref UsersPool
  UsersBeneficiariesGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Beneficiaries
      Description: Beneficiaries group
      UserPoolId: !Ref UsersPool
  # Database
  BeneficiariesTable:
    Properties:
      AttributeDefinitions:
        - AttributeName: user-sub
          AttributeType: S
        - AttributeName: unit
          AttributeType: S
      KeySchema:
        - AttributeName: user-sub
          KeyType: HASH
        - AttributeName: unit
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: beneficiaries
    Type: AWS::DynamoDB::Table
  ShopItemsTable:
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: category-release
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: category-release
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 2
      TableName: items
    Type: AWS::DynamoDB::Table
  TasksTable:
    Properties:
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
        - AttributeName: objective-timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: user
          KeyType: HASH
        - AttributeName: objective-timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: tasks
    Type: AWS::DynamoDB::Table
  DistrictsTable:
    Properties:
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: districts
    Type: AWS::DynamoDB::Table
  GroupsTable:
    Properties:
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
        - AttributeName: district-timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH
        - AttributeName: district-timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: groups
    Type: AWS::DynamoDB::Table
  # App
  DistrictsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pps/districts/
      Handler: app.handler
      Runtime: python3.8
      Layers:
        - !Ref PPSCore
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref DistrictsTable
      Events:
        ListDistricts:
          Type: Api
          Properties:
            Path: /api/districts/
            Method: get
            RestApiId: !Ref PPSAPI
        GetDistrict:
          Type: Api
          Properties:
            Path: /api/districts/{district}/
            Method: get
            RestApiId: !Ref PPSAPI
  GroupsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pps/groups/
      Handler: app.handler
      Runtime: python3.8
      Layers:
        - !Ref PPSCore
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref GroupsTable
        - DynamoDBReadPolicy:
            TableName:
              !Ref DistrictsTable
        - DynamoDBCrudPolicy:
            TableName:
              !Ref BeneficiariesTable
      Events:
        CreateGroup:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/
            Method: post
            RestApiId: !Ref PPSAPI
            RequestModel:
              Model: NewGroup
              Required: true
        ListGroups:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/
            Method: get
            RestApiId: !Ref PPSAPI
        GetGroup:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/
            Method: get
            RestApiId: !Ref PPSAPI
        JoinGroup:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/join/
            Method: post
            RestApiId: !Ref PPSAPI
            RequestModel:
              Model: Code
              Required: true
  ScoutersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pps/scouters/
      Handler: app.handler
      Runtime: python3.8
      Layers:
        - !Ref PPSCore
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref GroupsTable
        - Statement:
            - Sid: CognitoIDPAddUserToGroup
              Effect: Allow
              Action:
                - cognito-idp:AdminAddUserToGroup
              Resource: '*'
      Events:
        GetScouter:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/scouters/{sub}
            Method: get
            RestApiId: !Ref PPSAPI
        ListScouters:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/scouters/
            Method: get
            RestApiId: !Ref PPSAPI
        SignupScouter:
          Type: Api
          Properties:
            Path: /api/auth/scouters-signup/
            Method: post
            RestApiId: !Ref PPSAPI
            Auth:
              Authorizer: NONE
            RequestModel:
              Model: ScouterSignUp
              Required: true
  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pps/auth/
      Handler: app.handler
      Runtime: python3.8
      Layers:
        - !Ref PPSCore
      Policies:
        - Statement:
            - Sid: LoginPolicy
              Effect: Allow
              Action:
                - cognito-idp:AdminInitiateAuth
              Resource: '*'
      Events:
        ConfirmUser:
          Type: Api
          Properties:
            Path: /api/auth/confirm/
            Auth:
              Authorizer: NONE
            Method: post
            RestApiId: !Ref PPSAPI
            RequestModel:
              Model: Code
              Required: true
        LoginUser:
          Type: Api
          Properties:
            Path: /api/auth/login/
            Auth:
              Authorizer: NONE
            Method: post
            RestApiId: !Ref PPSAPI
            RequestModel:
              Model: Login
              Required: true
        RefreshToken:
          Type: Api
          Properties:
            Path: /api/auth/refresh/
            Auth:
              Authorizer: NONE
            Method: post
            RestApiId: !Ref PPSAPI
            RequestModel:
              Model: RefreshToken
              Required: true
  BeneficiariesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pps/beneficiaries/
      Handler: app.handler
      Runtime: python3.8
      Layers:
        - !Ref PPSCore
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref BeneficiariesTable
        - Statement:
            - Sid: CognitoIDPAddUserToGroup
              Effect: Allow
              Action:
                - cognito-idp:AdminAddUserToGroup
              Resource: '*'
      Events:
        ListBeneficiaries:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/{unit}/
            Method: get
            RestApiId: !Ref PPSAPI
        GetBeneficiary:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/{unit}/{sub}/
            Method: get
            RestApiId: !Ref PPSAPI
        SignupBeneficiary:
          Type: Api
          Properties:
            Path: /api/auth/beneficiaries-signup/
            Method: post
            RestApiId: !Ref PPSAPI
            Auth:
              Authorizer: NONE
            RequestModel:
              Model: BeneficiarySignUp
              Required: true
  GalleryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pps/gallery/
      Handler: app.handler
      Runtime: python3.8
      Layers:
        - !Ref PPSCore
      Policies:
        S3CrudPolicy:
          BucketName:
            !Ref S3BucketGallery
      Events:
        GetGalleryPictures:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/{unit}/{sub}/gallery/
            Method: get
            RestApiId: !Ref PPSAPI
        AddPictureToGallery:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/{unit}/{sub}/gallery/{index}/
            Method: post
            RestApiId: !Ref PPSAPI
        ReplaceGalleryPicture:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/{unit}/{sub}/gallery/{index}/
            Method: put
            RestApiId: !Ref PPSAPI
        GetAvatar:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/{unit}/{sub}/avatar/
            Method: get
            RestApiId: !Ref PPSAPI
        UpdateAvatar:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/{unit}/{sub}/avatar/
            Method: put
            RestApiId: !Ref PPSAPI
  ShopFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pps/beneficiaries/
      Handler: app.handler
      Runtime: python3.8
      Layers:
        - !Ref PPSCore
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref BeneficiariesTable
        - DynamoDBCrudPolicy:
            TableName:
              !Ref ShopItemsTable
      Events:
        ListShopCategoryItems:
          Type: Api
          Properties:
            Path: /api/shop/{category}/{release}/items/
            Method: get
            RestApiId: !Ref PPSAPI
        GetShopItem:
          Type: Api
          Properties:
            Path: /api/shop/{category}/{release}/items/{id}/
            Method: get
            RestApiId: !Ref PPSAPI
  TasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pps/tasks/
      Handler: app.handler
      Runtime: python3.8
      Layers:
        - !Ref PPSCore
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref BeneficiariesTable
        - DynamoDBCrudPolicy:
            TableName:
              !Ref TasksTable
      Events:
        ListTasks:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/{unit}/{sub}/tasks/
            Method: get
            RestApiId: !Ref PPSAPI
        FinishTask:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/{unit}/{sub}/tasks/{index}/finish
            Method: post
            RestApiId: !Ref PPSAPI
        StartTask:
          Type: Api
          Properties:
            Path: /api/districts/{district}/groups/{group}/beneficiaries/{unit}/{sub}/tasks/
            Method: post
            RestApiId: !Ref PPSAPI
            RequestModel:
              Model: StartObjective
              Required: true
  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Serverless website OA'
  CloudfrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Comment: "Cloudfront distribution for serverless website"
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: http2
        # List of origins that Cloudfront will connect to
        Origins:
          - Id: s3-website
            DomainName: !GetAtt S3BucketWebApp.DomainName
            S3OriginConfig:
              # Restricting Bucket access through an origin access identity
              OriginAccessIdentity:
                Fn::Sub: 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        # To connect the CDN to the origins you need to specify behaviours
        DefaultCacheBehavior:
          # Compress resources automatically ( gzip )
          Compress: 'true'
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
          TargetOriginId: s3-website
          ViewerProtocolPolicy: redirect-to-https
  S3BucketWebApp:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pps-webpage
  S3BucketGallery:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pps-gallery
  S3BucketWebAppPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketWebApp
      PolicyDocument:
        # Restricting access to cloudfront only.
        Statement:
          - Effect: Allow
            Action: 's3:GetObject'
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketWebApp}/*"
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"


Outputs:
  AppAPI:
    Description: "API Gateway endpoint URL for Prod stage for PPS API"
    Value: !Sub "https://${PPSAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/"
  CloudFront:
    Description: "CloudFront PPS web app domain"
    Value: !GetAtt CloudfrontDistribution.DomainName
  DistrictsFunction:
    Description: "Districts Lambda Function ARN"
    Value: !GetAtt DistrictsFunction.Arn
  DistrictsFunctionIamRole:
    Description: "Implicit IAM Role created for the districts service"
    Value: !GetAtt DistrictsFunctionRole.Arn
  GroupsFunction:
    Description: "Groups Lambda Function ARN"
    Value: !GetAtt GroupsFunction.Arn
  GroupsFunctionIamRole:
    Description: "Implicit IAM Role created for the groups service"
    Value: !GetAtt GroupsFunctionRole.Arn
  ObjectivesFunction:
    Description: "Objectives Lambda Function ARN"
    Value: !GetAtt ObjectivesFunction.Arn
  ObjectivesFunctionIamRole:
    Description: "Implicit IAM Role created for the objectives service"
    Value: !GetAtt ObjectivesFunctionRole.Arn
  ScoutersFunction:
    Description: "Scouters Lambda Function ARN"
    Value: !GetAtt ScoutersFunction.Arn
  ScoutersFunctionIamRole:
    Description: "Implicit IAM Role created for the scouters service"
    Value: !GetAtt ScoutersFunctionRole.Arn
