# This is a basic workflow to help you get started with Actions

name: Publish to AWS SAM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
    - master
    - release/*
    - develop
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install dependencies
        run: |
          pip install awscli
          pip install aws-sam-cli
          pip install -r pps/core-layer/requirements.txt
          pip install -r pps/core-layer/requirements.txt --target ./pps/core-layer/python
          pip install pytest
      - name: Run tests
        run: pytest .
      - name: Validate template
        run: sam validate
      - name: deploy
        if: ${{github.ref == 'refs/heads/master'}}
        run: sam build && sam deploy --no-confirm-changeset --capabilities CAPABILITY_NAMED_IAM --parameter-overrides EnvType=prod

